services:

  ## Messaging Implementations

  Domain\Bus: '@Application\Messaging\TransactionalMessageBus'
  Application\Messaging\Map\HandlerMap: '@Application\Messaging\Map\InMemoryHandlerMap'
  Application\Messaging\Transaction\Transaction: '@Application\Messaging\Transaction\PersistenceTransaction'
