services:

  ## Messaging Implementations

  Domain\Bus: '@Application\Messaging\TransactionalMessageBus'
  Application\Messaging\Map\HandlerMap: '@Application\Messaging\Map\InMemoryHandlerMap'
  Application\Messaging\Transaction\Transaction: '@Application\Messaging\Transaction\PersistenceTransaction'

  ## Normalizer/Serializer Implementations

  Application\Normalization\Normalizer: '@Application\Normalization\Normalizer\AggregateNormalizer'
  Application\Serialization\Serializer: '@Application\Serialization\Serializer\AggregateSerializer'

  ## Synchronization Implementations

  Application\Synchronization\Hub: '@Application\Synchronization\Hub\MercureHub'

  ## Repository Implementations

  Domain\Repository\Stations: '@Application\Repository\Stations'
  Domain\Repository\Channels: '@Application\Repository\Channels'
  Domain\Repository\Messages: '@Application\Repository\Messages'
  Domain\Repository\Users: '@Application\Repository\Users'
  Domain\Repository\Invitations: '@Application\Repository\Invitations'

  ## Events Implementations

  Domain\EventLog: '@Application\EventLog'

  ## Auth Implementations

  Application\Auth\Extractor: '@Application\Auth\Token\HS256Token'
  Application\Auth\Tokenizer: '@Application\Auth\Token\HS256Token'

  ## Security Implementations

  Domain\Security\AccessControl: '@Application\Security\AccessControl'
  Domain\Security\PasswordHasher: '@Application\Security\PasswordHasher'
  Domain\Security\UserProvider: '@Application\Security\UserProvider'
