services:

  ## Messaging Implementations

  Domain\Bus: '@Application\Messaging\TransactionalMessageBus'
  Application\Messaging\Map\HandlerMap: '@Application\Messaging\Map\InMemoryHandlerMap'
  Application\Messaging\Transaction\Transaction: '@Application\Messaging\Transaction\PersistenceTransaction'

  ## Normalizer/Serializer Implementations

  Application\Normalizer\Normalizer: '@Application\Normalizer\AggregateNormalizer'
  Application\Serializer\Serializer: '@Application\Serializer\AggregateSerializer'

  ## Synchronization Implementations

  Application\Synchronization\Hub: '@Application\Synchronization\Hub\MercureHub'

  ## Repository Implementations

  Domain\Repository\Stations: '@Application\Repository\Stations'
  Domain\Repository\Channels: '@Application\Repository\Channels'
  Domain\Repository\Messages: '@Application\Repository\Messages'

  ## Events Implementations

  Domain\EventLog: '@Application\EventLog'
