---
services:
  _defaults:
    autowire: true
    autoconfigure: true

  ## Auth

  Application\Auth\Token\HS256Token:
    $key: '%auth_token_key%'

  ## CLI

  Application\CLI\:
    resource: '%kernel.project_dir%/src/Application/CLI'

  ## Messaging

  Application\Messaging\Map\InMemoryHandlerMap:
    $handlers: !tagged_iterator { tag: app.message.handler }

  Application\Messaging\Transaction\PersistenceTransaction: ~

  Application\Messaging\TransactionalMessageBus:
    tags: ['message.bus']

  Application\Messaging\TraceableMessageBus:
    tags: ['message.bus']

  ## HTTP

  Application\HTTP\Controller\:
    resource: '%kernel.project_dir%/src/Application/HTTP/Controller'
    tags: [ controller.service_arguments ]

  ## Normalization

  Application\Normalizer\Internal\:
    resource: '%kernel.project_dir%/src/Application/Normalizer/Internal'
    tags: [ app.normalizer.internal ]

  Application\Normalizer\AggregateNormalizer:
    $normalizers: !tagged_iterator { tag: app.normalizer.internal }

  ## Serialization

  Application\Serializer\Internal\:
    resource: '%kernel.project_dir%/src/Application/Serializer/Internal'
    tags: [ app.serializer.internal ]

  Application\Serializer\AggregateSerializer:
    $serializers: !tagged_iterator { tag: app.serializer.internal }

  ## Synchorinzation

  Application\Synchronization\Hub\:
    resource: '%kernel.project_dir%/src/Application/Synchronization/Hub/'

  ## Repository

  Application\Repository\:
    resource: '%kernel.project_dir%/src/Application/Repository'

  ## Security

  Application\Security\:
    resource: '%kernel.project_dir%/src/Application/Security'

  ## Events

  Application\EventLog: ~
  Application\TraceableEventLog: ~

  Application\Event\Listener\:
    resource: '%kernel.project_dir%/src/Application/Event/Listener'
    tags: [ kernel.event_listener ]
