services:
  _defaults:
    autowire: true
    autoconfigure: true

  ## Messaging

  Application\Messaging\Map\InMemoryHandlerMap:
    $handlers: !tagged_iterator { tag: app.message.handler }

  Application\Messaging\Transaction\PersistenceTransaction: ~

  Application\Messaging\TransactionalMessageBus:
    tags: ['message.bus']

  Application\Messaging\TraceableMessageBus:
    tags: ['message.bus']

  ## HTTP

  Application\HTTP\Controller\:
    resource: '%kernel.project_dir%/src/Application/HTTP/Controller'
    tags: [ controller.service_arguments ]
