---
services:
  _defaults:
    autowire: true
    autoconfigure: true

  ## Auth

  Application\Auth\Token\HS256Token:
    $key: '%auth_token_key%'

  ## CLI

  Application\CLI\:
    resource: '%kernel.project_dir%/src/Application/CLI'

  ## Messenger

  Application\MessengerBus: ~

  ## HTTP

  Application\HTTP\Controller\:
    resource: '%kernel.project_dir%/src/Application/HTTP/Controller'
    tags: [ controller.service_arguments ]

  ## Normalization

  Application\Normalization\Normalizer\:
    resource: '%kernel.project_dir%/src/Application/Normalization/Normalizer'
    tags: [ app.normalizer ]

  Application\Normalization\Normalizer\AggregateNormalizer:
    $normalizers: !tagged_iterator { tag: app.normalizer }

  ## Serialization

  Application\Serialization\Serializer\:
    resource: '%kernel.project_dir%/src/Application/Serialization/Serializer'
    tags: [ app.serializer ]

  Application\Serialization\Serializer\AggregateSerializer:
    $serializers: !tagged_iterator { tag: app.serializer }

  ## Synchorinzation

  Application\Synchronization\Hub\:
    resource: '%kernel.project_dir%/src/Application/Synchronization/Hub/'

  ## Repository

  Application\Repository\:
    resource: '%kernel.project_dir%/src/Application/Repository'

  ## Security

  Application\Security\:
    resource: '%kernel.project_dir%/src/Application/Security'

  ## Events

  Application\EventLog: ~
  Application\TraceableEventLog: ~

  Application\Event\Listener\:
    resource: '%kernel.project_dir%/src/Application/Event/Listener'
    tags: [ kernel.event_listener ]

  ## Search

  Application\Search\Indexer\ElasticsearchIndexer: ~
  Application\Search\Configuration\YAMLProvider:
    arguments:
      $filePath: '%kernel.project_dir%/config/search/mapping/message.yml'
