---
services:
  _defaults:
    autowire: true
    autoconfigure: true

  Domain\:
    resource: '%kernel.project_dir%/src/Domain'
    exclude: '%kernel.project_dir%/src/Domain/{Model,Message}'

  Domain\Handler\:
    resource: '%kernel.project_dir%/src/Domain/Handler'
    tags: [ app.message.handler ]

  Domain\Security\Rule\:
    resource: '%kernel.project_dir%/src/Domain/Security/Rule'
    tags: [ domain.security.rule ]

  Domain\Handler\Config\GetHandler:
    arguments:
      $apiURL: '%api_url%'
    tags: [ app.message.handler ]

  Domain\Handler\Station\CreateDefaultChannelHandler:
    arguments:
      $defaultChannelName: '%default_channel_name%'
    tags: [ app.message.handler ]
