---
services:
  _defaults:
    autowire: true
    autoconfigure: true

  Domain\:
    resource: '%kernel.project_dir%/src/Domain'
    exclude: '%kernel.project_dir%/src/Domain/{Model,Message}'

  Domain\CommandHandler\:
    resource: '%kernel.project_dir%/src/Domain/CommandHandler'
    tags: [ messenger.message_handler ]

  Domain\Security\Rule\:
    resource: '%kernel.project_dir%/src/Domain/Security/Rule'
    tags: [ domain.security.rule ]

  Domain\CommandHandler\Config\GetHandler:
    arguments:
      $apiURL: '%api_url%'
    tags: [ messenger.message_handler ]

  Domain\CommandHandler\Station\CreateDefaultChannelHandler:
    arguments:
      $defaultChannelName: '%default_channel_name%'
    tags: [ messenger.message_handler ]
