---
services:
  _defaults:
    autowire: true
    autoconfigure: true

  ## Framework

  Infra\Symfony\:
    resource: '%kernel.project_dir%/src/Infra/Symfony'
    exclude: '%kernel.project_dir%/src/Infra/Symfony/{Controller,DataCollector,Kernel.php}'

  ## Listeners

  Infra\Symfony\Event\Listener\:
    resource: '%kernel.project_dir%/src/Infra/Symfony/Event/Listener'
    tags: [ kernel.event_listener ]

  Infra\Symfony\Event\Listener\AllowPreflightRequestListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, priority: 512 }

  Infra\Symfony\Event\Listener\DecodeRequestJSONBodyListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, priority: 128 }

  Infra\Symfony\Event\Listener\FormatExceptionResponseListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception, priority: -32 }

  Infra\Symfony\Event\Listener\HandleCORSPermissionListener:
    arguments:
      $defaultOriginHost: '%app_host%'
      $defaultOriginPort: '%app_port%'
      $allowedPorts: '%cors_allowed_ports%'
    tags:
      - { name: kernel.event_listener, event: kernel.response }

  ## Argument Value Resolvers

  Infra\Symfony\HttpKernel\ArgumentValueResolver\:
    resource: '%kernel.project_dir%/src/Infra/Symfony/HttpKernel/ArgumentValueResolver'
    tags:
      - { name: controller.argument_value_resolver, priority: 128 }

  ## Security Authenticators

  Infra\Symfony\Security\Authenticator\UserPasswordAuthenticator:
    arguments:
      $authRoute: '%auth_path%'

  ## Security Voters

  Infra\Symfony\Security\Voter\:
    resource: '%kernel.project_dir%/src/Infra/Symfony/Security/Voter'
    tags: [ security.voter ]

  Infra\Symfony\Security\Voter\DomainRuleVoter:
    $rules: !tagged_iterator domain.security.rule

  ## Faker

  Infra\Faker\Factory: ~
