services:
  _defaults:
    autowire: true
    autoconfigure: true

  ## Framework

  Infra\Framework\:
    resource: '%kernel.project_dir%/src/Infra/Framework'
    exclude: '%kernel.project_dir%/src/Infra/Framework/{Controller,Kernel.php}'

  ## Listeners

  Infra\Framework\Event\Listener\:
    resource: '%kernel.project_dir%/src/Infra/Framework/Event/Listener'
    tags: [ kernel.event_listener ]

  Infra\Framework\Event\Listener\DecodeRequestJSONBodyListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, priority: 128 }

  ## Argument Value Resolvers

  Infra\Framework\HttpKernel\ArgumentValueResolver\:
    resource: '%kernel.project_dir%/src/Infra/Framework/HttpKernel/ArgumentValueResolver'
    tags:
      - { name: controller.argument_value_resolver, priority: 128 }
