---
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  ## Test Services

  Infra\Doctrine\Truncater: ~
  Application\Search\Indexer\MockedIndexer: ~

  ## Test overrides

  Application\Synchronization\Hub: '@Application\Synchronization\Hub\MockedHub'
  Domain\EventLog: '@Application\TraceableEventLog'
  Domain\Search\Indexer: '@Application\Search\Indexer\MockedIndexer'

  ## Acceptance Test

  Test\Acceptance\:
    resource: '../tests/acceptance/*'

  Test\Acceptance\Helper\Validator:
    $schemasBasePath: '%schema_base_path%'
