---
version: '3.8'

services:
  http:
    image: zusoy/chatterer-http:develop
    build:
      context: apps/http
      target: dev
    ports:
      - '80:80'
      - '8081:8081'
    volumes:
      - ./apps/api/public/media:/usr/src/app/media

  api:
    image: zusoy/chatterer-api:develop
    build:
      context: apps/api
      target: dev
    env_file:
      - .env
    volumes:
      - ./apps/api:/usr/src/app

  client:
    image: zusoy/chatterer-client:develop
    command: 'yarn start'
    stdin_open: true
    build:
      context: apps/client
      target: dev
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./apps/client:/usr/src/app

  swagger:
    image: zusoy/chatterer-swagger:develop
    build:
      context: apps/api
      dockerfile: swagger.Dockerfile
    environment:
      URL: doc/api.yml
    volumes:
      - ./apps/api/doc:/usr/share/nginx/html/doc

  database:
    image: zusoy/chatterer-database:develop
    build:
      context: apps/database
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - database:/var/lib/mysql

  hub:
    build:
      context: apps/hub
    env_file:
      - .env
    environment:
      SERVER_NAME: ':80'
    ports:
      - '8080:80'

volumes:
  database: ~

