Domain\Model\Channel:
  type: entity

  embedded:
    id:
      class: Domain\Identity\Identifier
      columnPrefix: false

  uniqueConstraints:
    unique_name:
      columns: [ station_id, name ]

  fields:
    name:
      type: string
    description:
      type: string
      nullable: true
    createdAt:
      type: datetime_immutable
    updatedAt:
      type: datetime_immutable

  manyToOne:
    station:
      targetEntity: Station
      inversedBy: channels
      joinColumn:
        nullable: false
        onDelete: CASCADE

  manyToMany:
    users:
      targetEntity: User
      mappedBy: channels
      cascade: [ persist ]

  lifecycleCallbacks:
    preUpdate: [ 'touch' ]
