---
Domain\Model\Station:
  type: entity

  embedded:
    id:
      class: Domain\Identity\Identifier
      columnPrefix: false

  uniqueConstraints:
    unique_name:
      columns: [ name ]

  fields:
    name:
      type: string
    description:
      type: string
      nullable: true
    createdAt:
      type: datetime_immutable
    updatedAt:
      type: datetime_immutable

  oneToMany:
    channels:
      targetEntity: Channel
      mappedBy: station
      cascade: [ persist,remove ]

  manyToMany:
    users:
      targetEntity: User
      mappedBy: stations
      cascade: [ persist ]

  lifecycleCallbacks:
    preUpdate: [ 'touch' ]
