---
framework:
  messenger:
    buses:
      messenger.bus.default:
        middleware:
          - 'doctrine_transaction'

    transports:
      sync: 'sync://'

when@test:
  framework:
    messenger:
      transports:
        async: 'in-memory://'
