openapi: 3.0.1

info:
  title: Chatterer
  description: 'Chatterer API'
  version: 1.0.0
  contact:
    email: gregoire.drapeau@knplabs.com
    name: Flaggy

paths:
  /stations: { $ref: ./paths/stations.yml }

components:
  responses:
    invalid:
      description: Invalid payload specified
      content:
        application/json:
          schema:
            $ref: ./schema/error.json

  schemas:
    Station:
      $ref: ./schema/station-item.json
