openapi: 3.0.1

info:
  title: Chatterer
  description: 'Chatterer API'
  version: 1.0.0
  contact:
    email: gregoire.drapeau@knplabs.com
    name: Flaggy

paths:
  /config: { $ref: ./paths/config.yml }
  /stations: { $ref: ./paths/stations.yml }
  /station/{id}: { $ref: ./paths/station.yml }

components:
  parameters:
    id:
      schema:
        type: string
        pattern: ^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}$
      name: id
      in: path
      required: true

  responses:
    notfound:
      description: Not found
      content:
        application/json:
          schema:
            $ref: ./schema/error.json

    invalid:
      description: Invalid payload specified
      content:
        application/json:
          schema:
            $ref: ./schema/error.json

  schemas:
    Config:
      $ref: ./schema/config.json
    Station:
      $ref: ./schema/station-item.json
