---
openapi: 3.0.1

info:
  title: Chatterer
  description: 'Chatterer API'
  version: 1.0.0
  contact:
    email: gregoire.drapeau79@gmail.com
    name: Zusoy

paths:
  # Config
  /config: { $ref: ./paths/config.yml }

  # User
  /register: { $ref: ./paths/register.yml }
  /users: { $ref: ./paths/users.yaml }

  # Station
  /stations: { $ref: ./paths/stations.yml }
  /station/{id}: { $ref: ./paths/station.yml }
  /station/{id}/invite: { $ref: ./paths/station-invite.yml }
  /station/{id}/join: { $ref: ./paths/station-join.yml }
  /station/{id}/users: { $ref: ./paths/station-users.yml }

  # Channel
  /station/{id}/channels: { $ref: ./paths/channels.yml }
  /channel/{id}: { $ref: ./paths/channel.yml }
  /channel/{id}/join: { $ref: ./paths/channel-join.yml }
  /channel/{id}/users: { $ref: ./paths/channel-users.yml }

  # Message
  /channel/{id}/messages: { $ref: ./paths/messages.yml }
  /message/{id}: { $ref: ./paths/message.yml }

components:
  parameters:
    id:
      schema:
        type: string
        pattern: ^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}$
      name: id
      in: path
      required: true

  responses:
    notfound:
      description: Not found
      content:
        application/json:
          schema:
            $ref: ./schema/error.json

    invalid:
      description: Invalid payload specified
      content:
        application/json:
          schema:
            $ref: ./schema/error.json

    forbidden:
      description: Operation denied
      content:
        application/json:
          schema:
            $ref: ./schema/error.json

    unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ./schema/error.json

  schemas:
    Config:
      $ref: ./schema/config.json
    Station:
      $ref: ./schema/station-item.json
    Channel:
      $ref: ./schema/channel-item.json
    Message:
      $ref: ./schema/message-item.json
    User:
      $ref: ./schema/user-item.json
    Invitation:
      $ref: ./schema/invitation-item.json
