---
name: Client

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  client_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x ]

  steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build and test
      run: |
        yarn install
        yarn run build --if-present
        yarn test
